version: "3.8"
services:
  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  backend:
    build: ./backend
    command: npm run start:dev
    volumes:
      - ./backend:/app
    ports:
      - "4000:4000"
    depends_on:
      - mongo
      - redis

  worker:
    build: ./worker
    command: npm run start
    volumes:
      - ./worker:/app
    depends_on:
      - redis

  # vendor-sim:
  #   build: ./vendor-sim
  #   command: npm run start
  #   volumes:
  #     - ./vendor-sim:/app
  #   ports:
  #     - "5000:5000"

volumes:
  mongo-data:
